# Generated by Django 4.1.4 on 2022-12-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=45)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('adresse', models.CharField(max_length=45)),
                ('sexe', models.CharField(choices=[('Homme', 'homme'), ('Femme', 'femme')], max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('datenaissance', models.DateField(max_length=45)),
            ],
        ),
    ]
