# Generated by Django 4.1.4 on 2022-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anneescolaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('sexe', models.CharField(choices=[('Garcon', 'garcon'), ('Fille', 'fille')], max_length=45)),
                ('adresse', models.CharField(max_length=45)),
                ('lieunaissance', models.CharField(max_length=45)),
            ],
        ),
    ]
