# Generated by Django 4.1.4 on 2022-12-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.CharField(max_length=45)),
                ('nom_cours', models.CharField(max_length=45)),
            ],
        ),
    ]
