# Generated by Django 4.1.4 on 2022-12-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('periode', models.CharField(choices=[('Trimestre 1', 'trimestre 1'), ('Trimestre 2', 'trimestre 2'), ('Trimestre 3', 'trimestre 3')], max_length=45)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classe')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cour')),
                ('enseignante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enseignante')),
            ],
        ),
    ]
