# Generated by Django 4.1.4 on 2022-12-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=45)),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.anneescolaire')),
                ('enseignante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enseignante')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tache')),
            ],
        ),
    ]
