from .enseignante import Enseignante
from .anneescolaire import Anneescolaire
from .elev import Elev
from .parent import Parent
from .classe import Classe
from .inscription import Inscription
from .cour import Cour
from .tache import Tache
from .test import Test
from .fonction import Fonction
from .attribution import Attribution